package entities;
// Generated Feb 12, 2016 2:24:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private int id;
     private String surname;
     private String otherNames;
     private String gender;
     private String maritalStatus;
     private String email;
     private String occupation;
     private String groupName;
     private String phoneNumber;
     private String address;
     private String country;
     private String state;
     private String lga;
     private Date dob;
     private Date isuingDate;
     private String pictureurl;
     private String issuingName;
     private Account accountNumber;
     private String passBookNumber;

    public Customer() {
    }

	
    public Customer(Account accountNumber) {
        this.accountNumber = accountNumber;
    }
    public Customer(String surname, String otherNames, String gender, String maritalStatus, String email, String occupation, String groupName, String phoneNumber, String address, String country, String state, String lga, Date dob, Date isuingDate, String pictureurl, String issuingName, Account accountNumber) {
       this.surname = surname;
       this.otherNames = otherNames;
       this.gender = gender;
       this.maritalStatus = maritalStatus;
       this.email = email;
       this.occupation = occupation;
       this.groupName = groupName;
       this.phoneNumber = phoneNumber;
       this.address = address;
       this.country = country;
       this.state = state;
       this.lga = lga;
       this.dob = dob;
       this.isuingDate = isuingDate;
       this.pictureurl = pictureurl;
       this.issuingName = issuingName;
       this.accountNumber = accountNumber;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getOtherNames() {
        return this.otherNames;
    }
    
    public void setOtherNames(String otherNames) {
        this.otherNames = otherNames;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getLga() {
        return this.lga;
    }
    
    public void setLga(String lga) {
        this.lga = lga;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public Date getIsuingDate() {
        return this.isuingDate;
    }
    
    public void setIsuingDate(Date isuingDate) {
        this.isuingDate = isuingDate;
    }
    public String getPictureurl() {
        return this.pictureurl;
    }
    
    public void setPictureurl(String pictureurl) {
        this.pictureurl = pictureurl;
    }
    public String getIssuingName() {
        return this.issuingName;
    }
    
    public void setIssuingName(String issuingName) {
        this.issuingName = issuingName;
    }
    public Account getAccountNumber() {
        return this.accountNumber;
    }
    
    public void setAccountNumber(Account accountNumber) {
        this.accountNumber = accountNumber;
    }

    public String getPassBookNumber() {
        return passBookNumber;
    }

    public void setPassBookNumber(String passBookNumber) {
        this.passBookNumber = passBookNumber;
    }




}


