package entities;
// Generated Feb 12, 2016 2:24:18 PM by Hibernate Tools 4.3.1



/**
 * Databaseset generated by hbm2java
 */
public class Databaseset  implements java.io.Serializable {


     private int id;
     private Boolean account;
     private Boolean groups;
     private Boolean customer;
     private Boolean transact;
     private Boolean settings;
     private Boolean loanrepayment;
     private Boolean loan;

    public Databaseset() {
    }

	
    public Databaseset(int id) {
        this.id = id;
    }
    public Databaseset( Boolean account, Boolean groups, Boolean customer, Boolean transact, Boolean settings, Boolean loanrepayment, Boolean loan) {
       this.id = id;
       this.account = account;
       this.groups = groups;
       this.customer = customer;
       this.transact = transact;
       this.settings = settings;
       this.loanrepayment = loanrepayment;
       this.loan = loan;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Boolean getAccount() {
        return this.account;
    }
    
    public void setAccount(Boolean account) {
        this.account = account;
    }
    public Boolean getGroups() {
        return this.groups;
    }
    
    public void setGroups(Boolean groups) {
        this.groups = groups;
    }
    public Boolean getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Boolean customer) {
        this.customer = customer;
    }
    public Boolean getTransact() {
        return this.transact;
    }
    
    public void setTransact(Boolean transact) {
        this.transact = transact;
    }
    public Boolean getSettings() {
        return this.settings;
    }
    
    public void setSettings(Boolean settings) {
        this.settings = settings;
    }
    public Boolean getLoanrepayment() {
        return this.loanrepayment;
    }
    
    public void setLoanrepayment(Boolean loanrepayment) {
        this.loanrepayment = loanrepayment;
    }
    public Boolean getLoan() {
        return this.loan;
    }
    
    public void setLoan(Boolean loan) {
        this.loan = loan;
    }




}


