package entities;
// Generated Feb 12, 2016 2:24:18 PM by Hibernate Tools 4.3.1



/**
 * Groups generated by hbm2java
 */
public class Groups  implements java.io.Serializable {


     private String groupName;
     private String groupNo;

    public Groups() {
    }

	
    public Groups(String groupName) {
        this.groupName = groupName;
    }
    public Groups(String groupName, String groupNo) {
       this.groupName = groupName;
       this.groupNo = groupNo;
    }
   
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public String getGroupNo() {
        return this.groupNo;
    }
    
    public void setGroupNo(String groupNo) {
        this.groupNo = groupNo;
    }




}


