package entities;
// Generated Feb 12, 2016 2:24:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Loanrepayment generated by hbm2java
 */
public class Loanrepayment  implements java.io.Serializable {


     private int loanId;
     private String customerLoanNumber;
     private Date paydate;
     private Double amount;

    public Loanrepayment() {
    }

    public Loanrepayment(String customerLoanNumber, Date paydate, Double amount) {
       this.customerLoanNumber = customerLoanNumber;
       this.paydate = paydate;
       this.amount = amount;
    }
   
    public int getLoanId() {
        return this.loanId;
    }
    
    public void setLoanId(int loanId) {
        this.loanId = loanId;
    }
    public String getCustomerLoanNumber() {
        return this.customerLoanNumber;
    }
    
    public void setCustomerLoanNumber(String customerLoanNumber) {
        this.customerLoanNumber = customerLoanNumber;
    }
    public Date getPaydate() {
        return this.paydate;
    }
    
    public void setPaydate(Date paydate) {
        this.paydate = paydate;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }




}


