package entities;
// Generated Feb 12, 2016 2:24:18 PM by Hibernate Tools 4.3.1



/**
 * Setting generated by hbm2java
 */
public class Setting  implements java.io.Serializable {


     private int id;
     private String username;
     private String password;
     private String pictureurl;
     private Boolean skipformcheck;
     private Boolean snapshot;
     private Boolean screenshot;
     private String stylesheet;

    public Setting() {
    }

	
    public Setting(int id) {
        this.id = id;
    }
    public Setting(String username, String password, String pictureurl, Boolean skipformcheck, Boolean snapshot, Boolean screenshot, String stylesheet) {
      // this.id = id;
       this.username = username;
       this.password = password;
       this.pictureurl = pictureurl;
       this.skipformcheck = skipformcheck;
       this.snapshot = snapshot;
       this.screenshot = screenshot;
       this.stylesheet = stylesheet;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPictureurl() {
        return this.pictureurl;
    }
    
    public void setPictureurl(String pictureurl) {
        this.pictureurl = pictureurl;
    }
    public Boolean getSkipformcheck() {
        return this.skipformcheck;
    }
    
    public void setSkipformcheck(Boolean skipformcheck) {
        this.skipformcheck = skipformcheck;
    }
    public Boolean getSnapshot() {
        return this.snapshot;
    }
    
    public void setSnapshot(Boolean snapshot) {
        this.snapshot = snapshot;
    }
    public Boolean getScreenshot() {
        return this.screenshot;
    }
    
    public void setScreenshot(Boolean screenshot) {
        this.screenshot = screenshot;
    }
    public String getStylesheet() {
        return this.stylesheet;
    }
    
    public void setStylesheet(String stylesheet) {
        this.stylesheet = stylesheet;
    }




}


